// Dados de seed — espelham o que estava em lib/data.ts (Fase 1).
// Usado por prisma/seed.ts para popular o banco na primeira execução.
// categoryId/storeId aqui são SLUGS (igual ao modelo da Fase 1).

function img(text: string): string {
  return `https://placehold.co/600x400/f1f5f9/0f172a?text=${encodeURIComponent(text)}`;
}

export const stores = [
  { id: "amazon", slug: "amazon", name: "Amazon", color: "#ff9900" },
  { id: "mercadolivre", slug: "mercado-livre", name: "Mercado Livre", color: "#ffe600" },
  { id: "shopee", slug: "shopee", name: "Shopee", color: "#ee4d2d" },
  { id: "magalu", slug: "magalu", name: "Magalu", color: "#0086ff" },
];

export const categories = [
  { id: "eletronicos", slug: "eletronicos", name: "Eletrônicos", icon: "🔌", description: "Fones, TVs, smartwatches e mais." },
  { id: "suplementos", slug: "suplementos", name: "Suplementos", icon: "💊", description: "Whey, creatina, pré-treino e vitaminas." },
  { id: "academia", slug: "academia", name: "Academia", icon: "🏋️", description: "Equipamentos e acessórios de treino." },
  { id: "celulares", slug: "celulares", name: "Celulares", icon: "📱", description: "Smartphones, capas e acessórios." },
  { id: "games", slug: "games", name: "Games", icon: "🎮", description: "Consoles, jogos e periféricos." },
  { id: "casa", slug: "casa", name: "Casa", icon: "🏠", description: "Utensílios, decoração e organização." },
  { id: "ferramentas", slug: "ferramentas", name: "Ferramentas", icon: "🔧", description: "Furadeiras, kits e acessórios." },
  { id: "moda", slug: "moda", name: "Moda", icon: "👕", description: "Roupas, calçados e acessórios." },
];

export const offers = [
  {
    id: "whey-growth-1kg",
    slug: "growth-basic-whey-1kg",
    title: "Growth Basic Whey 1kg",
    shortDescription: "Whey concentrado, 1kg, sabor chocolate. Ótimo custo-benefício.",
    categoryId: "suplementos",
    storeId: "amazon",
    originalPrice: 109.9,
    currentPrice: 72.9,
    affiliateUrl: "https://exemplo.com/aff/whey-growth",
    imageUrl: img("Whey 1kg"),
    createdAt: "2026-07-13",
    priceHistory: [
      { price: 109.9, capturedAt: "2026-07-01" },
      { price: 99.9, capturedAt: "2026-07-07" },
      { price: 72.9, capturedAt: "2026-07-13" },
    ],
  },
  {
    id: "creatina-black-skull",
    slug: "creatina-black-skull-300g",
    title: "Creatina Black Skull 300g",
    shortDescription: "Creatina micronizada, 300g. Aumenta força e explosão.",
    categoryId: "suplementos",
    storeId: "mercado-livre",
    originalPrice: 89.9,
    currentPrice: 59.9,
    affiliateUrl: "https://exemplo.com/aff/creatina-bs",
    imageUrl: img("Creatina 300g"),
    createdAt: "2026-07-12",
    priceHistory: [
      { price: 89.9, capturedAt: "2026-07-01" },
      { price: 59.9, capturedAt: "2026-07-12" },
    ],
  },
  {
    id: "fone-jbl-tune",
    slug: "jbl-tune-510bt",
    title: "Fone JBL Tune 510BT",
    shortDescription: "Bluetooth, cancelamento passivo, 40h de bateria.",
    categoryId: "eletronicos",
    storeId: "amazon",
    originalPrice: 249.9,
    currentPrice: 149.9,
    affiliateUrl: "https://exemplo.com/aff/jbl-510",
    imageUrl: img("Fone JBL"),
    createdAt: "2026-07-13",
    priceHistory: [
      { price: 249.9, capturedAt: "2026-06-20" },
      { price: 179.9, capturedAt: "2026-07-05" },
      { price: 149.9, capturedAt: "2026-07-13" },
    ],
  },
  {
    id: "smartwatch-mi-band",
    slug: "xiaomi-smart-band-9",
    title: "Xiaomi Smart Band 9",
    shortDescription: "Monitora sono, batimento e 21 dias de bateria.",
    categoryId: "eletronicos",
    storeId: "shopee",
    originalPrice: 299.9,
    currentPrice: 199.9,
    affiliateUrl: "https://exemplo.com/aff/mi-band-9",
    imageUrl: img("Smart Band 9"),
    createdAt: "2026-07-11",
    priceHistory: [
      { price: 299.9, capturedAt: "2026-07-01" },
      { price: 199.9, capturedAt: "2026-07-11" },
    ],
  },
  {
    id: "iphone-15",
    slug: "iphone-15-128gb",
    title: "iPhone 15 128GB",
    shortDescription: "Chip A16, câmera 48MP, USB-C. Novo e lacrado.",
    categoryId: "celulares",
    storeId: "magalu",
    originalPrice: 4299.0,
    currentPrice: 3699.0,
    affiliateUrl: "https://exemplo.com/aff/iphone-15",
    imageUrl: img("iPhone 15"),
    createdAt: "2026-07-13",
    priceHistory: [
      { price: 4299.0, capturedAt: "2026-07-01" },
      { price: 3699.0, capturedAt: "2026-07-13" },
    ],
  },
  {
    id: "capa-silicone-samsung",
    slug: "capa-silicone-galaxy-s24",
    title: "Capa de Silicone Galaxy S24",
    shortDescription: "Proteção reforçada, antiderrapante, várias cores.",
    categoryId: "celulares",
    storeId: "shopee",
    originalPrice: 49.9,
    currentPrice: 19.9,
    affiliateUrl: "https://exemplo.com/aff/capa-s24",
    imageUrl: img("Capa S24"),
    createdAt: "2026-07-10",
    priceHistory: [
      { price: 49.9, capturedAt: "2026-07-01" },
      { price: 19.9, capturedAt: "2026-07-10" },
    ],
  },
  {
    id: "controle-xbox",
    slug: "controle-xbox-series-wireless",
    title: "Controle Xbox Wireless",
    shortDescription: "Bluetooth, compatível com PC e console. Cor preta.",
    categoryId: "games",
    storeId: "amazon",
    originalPrice: 399.9,
    currentPrice: 279.9,
    affiliateUrl: "https://exemplo.com/aff/controle-xbox",
    imageUrl: img("Controle Xbox"),
    createdAt: "2026-07-12",
    priceHistory: [
      { price: 399.9, capturedAt: "2026-07-01" },
      { price: 279.9, capturedAt: "2026-07-12" },
    ],
  },
  {
    id: "playstation-5",
    slug: "ps5-standard-825gb",
    title: "PlayStation 5 Edição Standard",
    shortDescription: "SSD 825GB, controle DualSense, mídia física.",
    categoryId: "games",
    storeId: "magalu",
    originalPrice: 3999.0,
    currentPrice: 3399.0,
    affiliateUrl: "https://exemplo.com/aff/ps5",
    imageUrl: img("PS5"),
    createdAt: "2026-07-13",
    priceHistory: [
      { price: 3999.0, capturedAt: "2026-07-01" },
      { price: 3399.0, capturedAt: "2026-07-13" },
    ],
  },
  {
    id: "halter-adjustable",
    slug: "halter-ajustavel-24kg",
    title: "Halter Ajustável 24kg",
    shortDescription: "Substitui um kit de pesos. Ideal para casa.",
    categoryId: "academia",
    storeId: "mercado-livre",
    originalPrice: 599.9,
    currentPrice: 399.9,
    affiliateUrl: "https://exemplo.com/aff/halter-24",
    imageUrl: img("Halter 24kg"),
    createdAt: "2026-07-09",
    priceHistory: [
      { price: 599.9, capturedAt: "2026-07-01" },
      { price: 399.9, capturedAt: "2026-07-09" },
    ],
  },
  {
    id: "tapete-crossfit",
    slug: "tapete-academia-15mm",
    title: "Tapete de Academia 15mm",
    shortDescription: "Antiderrapante, 1,80m x 0,80m. Protege o piso.",
    categoryId: "academia",
    storeId: "shopee",
    originalPrice: 159.9,
    currentPrice: 99.9,
    affiliateUrl: "https://exemplo.com/aff/tapete",
    imageUrl: img("Tapete 15mm"),
    createdAt: "2026-07-08",
    priceHistory: [
      { price: 159.9, capturedAt: "2026-07-01" },
      { price: 99.9, capturedAt: "2026-07-08" },
    ],
  },
  {
    id: "furadeira-vonder",
    slug: "furadeira-vonder-550w",
    title: "Furadeira Vonder 550W",
    shortDescription: "Pistola, 550W, maleta com bits inclusos.",
    categoryId: "ferramentas",
    storeId: "magalu",
    originalPrice: 219.9,
    currentPrice: 149.9,
    affiliateUrl: "https://exemplo.com/aff/furadeira-vonder",
    imageUrl: img("Furadeira Vonder"),
    createdAt: "2026-07-11",
    priceHistory: [
      { price: 219.9, capturedAt: "2026-07-01" },
      { price: 149.9, capturedAt: "2026-07-11" },
    ],
  },
  {
    id: "kit-ferramentas",
    slug: "kit-ferramentas-130-pecas",
    title: "Kit de Ferramentas 130 peças",
    shortDescription: "Chaves, bits e alicates em maleta organizada.",
    categoryId: "ferramentas",
    storeId: "mercado-livre",
    originalPrice: 179.9,
    currentPrice: 119.9,
    affiliateUrl: "https://exemplo.com/aff/kit-130",
    imageUrl: img("Kit 130pcs"),
    createdAt: "2026-07-07",
    priceHistory: [
      { price: 179.9, capturedAt: "2026-07-01" },
      { price: 119.9, capturedAt: "2026-07-07" },
    ],
  },
  {
    id: "cafeteira-electrolux",
    slug: "cafeteira-electrolux-15-bar",
    title: "Cafeteira Electrolux 15 bar",
    shortDescription: "Espresso automático, 15 bar, 1,2L.",
    categoryId: "casa",
    storeId: "amazon",
    originalPrice: 499.9,
    currentPrice: 349.9,
    affiliateUrl: "https://exemplo.com/aff/cafeteira",
    imageUrl: img("Cafeteira 15bar"),
    createdAt: "2026-07-13",
    priceHistory: [
      { price: 499.9, capturedAt: "2026-07-01" },
      { price: 349.9, capturedAt: "2026-07-13" },
    ],
  },
  {
    id: "organizador-cozinha",
    slug: "organizador-cozinha-aco",
    title: "Organizador de Cozinha Inox",
    shortDescription: "Suporte para talheres e temperos, aço escovado.",
    categoryId: "casa",
    storeId: "shopee",
    originalPrice: 89.9,
    currentPrice: 39.9,
    affiliateUrl: "https://exemplo.com/aff/organizador",
    imageUrl: img("Organizador"),
    createdAt: "2026-07-06",
    priceHistory: [
      { price: 89.9, capturedAt: "2026-07-01" },
      { price: 39.9, capturedAt: "2026-07-06" },
    ],
  },
  {
    id: "camiseta-basica",
    slug: "camiseta-basica-premium",
    title: "Camiseta Básica Premium",
    shortDescription: "Algodão pima, gola redonda, várias cores.",
    categoryId: "moda",
    storeId: "shopee",
    originalPrice: 79.9,
    currentPrice: 34.9,
    affiliateUrl: "https://exemplo.com/aff/camiseta",
    imageUrl: img("Camiseta"),
    createdAt: "2026-07-10",
    priceHistory: [
      { price: 79.9, capturedAt: "2026-07-01" },
      { price: 34.9, capturedAt: "2026-07-10" },
    ],
  },
  {
    id: "tenis-corrida",
    slug: "tenis-corrida-leve",
    title: "Tênis de Corrida Leve",
    shortDescription: "Solado responsivo, ideal para treinos diários.",
    categoryId: "moda",
    storeId: "mercado-livre",
    originalPrice: 399.9,
    currentPrice: 249.9,
    affiliateUrl: "https://exemplo.com/aff/tenis",
    imageUrl: img("Tênis Corrida"),
    createdAt: "2026-07-12",
    priceHistory: [
      { price: 399.9, capturedAt: "2026-07-01" },
      { price: 249.9, capturedAt: "2026-07-12" },
    ],
  },
  {
    id: "Ventilador-de-Mesa",
    slug: "ventilador-de-mesa",
    title: "Ventilador de Mesa 40 cm 10 Pás com 3 Velocidades Ventisol Turbo 10",
    shortDescription: "Mais conforto, tecnologia e praticidade para o seu ambiente!",
    categoryId: "casa",
    storeId: "shopee",
    originalPrice: 149.9,
    currentPrice: 141.41,
    affiliateUrl: "https://s.shopee.com.br/70IX4X7Exc",
    imageUrl: "/ofertas/ventilador1.jpeg",
    createdAt: "2026-07-12",
    priceHistory: [
      { price: 149.9, capturedAt: "2026-07-01" },
      { price: 141.41, capturedAt: "2026-07-12" },
    ],
  },
];
